@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyTaskList" as ReadOnlyTaskList
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class TaskList
Class ModelManager
Class UserPrefs

Class UniqueTaskList
Class Task
Class Name
Class Description
Class Deadline
Class CompletionStatus
Class Tag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TaskList .up.|> ReadOnlyTaskList

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyTaskList
ModelManager -left-> "1" TaskList
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TaskList *--> "1" UniqueTaskList
UniqueTaskList --> "~* all" Task
Task *--> Name
Task *--> CompletionStatus
Task *--> Description
Task *--> Deadline
Task *--> "*" Tag

Name -[hidden]right-> Description
Description -[hidden]right-> Deadline
Deadline -[hidden]right-> CompletionStatus

ModelManager -->"~* filtered" Task
@enduml
