@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HarmoniaParser" as HarmoniaParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTaskList" as VersionedTaskList MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> HarmoniaParser : parseCommand(undo)
activate HarmoniaParser

create UndoCommand
HarmoniaParser -> UndoCommand
activate UndoCommand

UndoCommand --> HarmoniaParser
deactivate UndoCommand

HarmoniaParser --> LogicManager : u
deactivate HarmoniaParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoTaskList()
activate Model

Model -> VersionedTaskList : undo()
activate VersionedTaskList

VersionedTaskList -> VersionedTaskList :resetData(ReadOnlyTaskList)
VersionedTaskList --> Model :
deactivate VersionedTaskList

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
